### PR TITLE
Added code to update CSP policy header based on custom site url

### LINKED ISSUE #59: Make feature work with new CSP feature in core
In https://github.com/matomo-org/matomo/pull/17798 we added CSP headers.

When  this setting is configured
image

I would assume that tracking requests no longer work to an external Matomo.  We would need to adjust the security policy using DI on all pages to allow the configured domain/src.

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Added code to update CSP policy header based on custom site url,
Fixes: #59 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by justinvelluppillai — COMMENTED** [review]
looks good to me. @tsteur maybe to give the final ok?

**Comment by tsteur** [comment]
Looks good to me @justinvelluppillai 

Could check if a host was actually returned by `parse_url($customSiteUrl, PHP_URL_HOST)` but as we're checking that the configured url looks like a URL I suppose this should be always the case anyway.

**Comment by AltamashShaikh** [comment]
@tsteur Added check for host

**Review by tsteur — CHANGES_REQUESTED** [review]
@AltamashShaikh @justinvelluppillai I actually just noticed a problem... if the plugin was used with a version before Matomo 4.5 where the security class does not exist, it would probably cause a fatal error.

I'm thinking there are 2 solutions to this.

* In `plugin.json` we could increase the required Matomo version so the plugin will only work with a newer Matomo version. I'm not 100% sure though this would actually help in that case if someone installs the plugin update manually
* Maybe using `'\Piwik\View\SecurityPolicy'` instead of `\Piwik\View\SecurityPolicy::class` be better as I think this way it shouldn't cause an issue.

**Pull request merged**
