### PR TITLE
update expected test file for #20592 in matomo core

### PR DESCRIPTION
**Pull request by diosmosis**
### Description:

Depends on https://github.com/matomo-org/matomo/pull/20592

As title.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by snake14** [comment]
@diosmosis Why is this change necessary? The builds are currently passing on 4.x-dev.

**Comment by diosmosis** [comment]
@snake14 its to fix the build if/when matomo-org/matomo#20592 is merged. It's a preemptive build fix. (which is therea no needs review label)

**Comment by snake14** [comment]
@diosmosis It looks like the core PR didn't get merged. Should this PR be closed? We're trying to create beta releases for the plugins and I wanted to make sure whether I need to wait for these changes to be merged.

**Comment by diosmosis** [comment]
@snake14 these changes don't have to be merged right now. We can make this PR a draft if you want.

**Comment by snake14** [comment]
Thank you @diosmosis . I'll mark this PR as needing to be migrated to 5.x

**Pull request merged**
