### PR TITLE
use HTTPS everywhere

### PR DESCRIPTION
**Pull request by Findus23**
Sending data unencrypted over the internet shouldn't be necessary anymore.

I didn't test this, so I'll wait for the test results.

### CODE REVIEW

**Comment by tsteur** [comment]
Looks good to merge when tests pass 👍

**Comment by Findus23** [comment]
Not sure why the remaining two tests are failing (the third one is also failing on master)

**Comment by tsteur** [comment]
There are still some failing cause it is still referring to http? `trackingDomain":"http:\/\/demo-anonymous.matomo.org","exampleDomain":"http:\/\/example.com","userId`

**Comment by Findus23** [comment]
Ah, didn't notice that they were hardcoded strings. (And didn't find them because of the encoding)

**Pull request merged**
